title: Mathematical Economics
description: A Jekyll theme for documentation
baseurl: "/Game_Theory" # the subpath of your site, e.g. /blog

theme: just-the-docs

url: https://drpeteawag.github.io/Game_Theory/

